#!/usr/bin/env ruby
require_relative './cmachinegrammar'
require_relative './cmachine'
require 'pp'

source = File.read(ARGV[0])
ast = CMachineGrammar.parse(source)
context = CMachineGrammar::CompileData.new
code = ast.map {|node| node.compile(context)}
require 'pry'; binding.pry
machine = CMachine.new(code)
open('code', 'w') {|f| f.puts code}
require 'pry'; binding.pry
