#!/usr/bin/env ruby
require_relative './cmachinegrammar'
require_relative './cmachine'
require 'pp'

source = File.read(ARGV[0])
ast = CMachineGrammar.parse(source)
context = CMachineGrammar::CompileData.new
code = ast.compile(context)
machine = CMachine.new(code)
require 'pry'; binding.pry
